import { PrismaClient } from '@prisma/client';

/**
 * Seed sample customers
 * Includes: Retail, Wholesale, and Distributor customers
 */
export async function seedCustomers(prisma: PrismaClient): Promise<void> {
  console.log('  🏪 Seeding Retail Customers...');
  
  // Retail Customers (10 samples)
  const retailCustomers = [
    {
      code: 'RETAIL001',
      name: 'ABC Retail Store',
      email: 'contact@abcretail.com',
      phone: '+91-9876543210',
      mobile: '+91-9876543210',
      contactPerson: 'Rajesh Kumar',
      contactEmail: 'rajesh@abcretail.com',
      contactPhone: '+91-9876543210',
      creditLimit: 25000,
      creditTermsDays: 30,
      taxNumber: 'GST29AAECA1234F1Z5',
      customerType: 'retail',
      statusValue: 'Active',
      paymentTermValue: 'Net 30',
      salesRepValue: 'John Smith',
      groupValue: 'Standard',
      notes: 'Regular retail customer, good payment history',
    },
    {
      code: 'RETAIL002',
      name: 'XYZ Boutique',
      email: 'info@xyzboutique.com',
      phone: '+91-9876543211',
      mobile: '+91-9876543211',
      contactPerson: 'Priya Sharma',
      contactEmail: 'priya@xyzboutique.com',
      contactPhone: '+91-9876543211',
      creditLimit: 35000,
      creditTermsDays: 30,
      taxNumber: 'GST27BBFCB2345G2Y6',
      customerType: 'retail',
      statusValue: 'Active',
      paymentTermValue: 'Net 30',
      salesRepValue: 'Sarah Johnson',
      groupValue: 'Premium',
      notes: 'Premium boutique, fashion items',
    },
    {
      code: 'RETAIL003',
      name: 'Fashion Hub',
      email: 'sales@fashionhub.com',
      phone: '+91-9876543212',
      mobile: '+91-9876543212',
      contactPerson: 'Amit Patel',
      contactEmail: 'amit@fashionhub.com',
      contactPhone: '+91-9876543212',
      creditLimit: 20000,
      creditTermsDays: 30,
      taxNumber: 'GST19CCDDC3456H3X7',
      customerType: 'retail',
      statusValue: 'Active',
      paymentTermValue: 'Net 30',
      salesRepValue: 'Mike Davis',
      groupValue: 'Standard',
      notes: 'Fashion retail chain outlet',
    },
    {
      code: 'RETAIL004',
      name: 'Electronics Store',
      email: 'info@electrostore.com',
      phone: '+91-9876543213',
      mobile: '+91-9876543213',
      contactPerson: 'Suresh Reddy',
      contactEmail: 'suresh@electrostore.com',
      contactPhone: '+91-9876543213',
      creditLimit: 50000,
      creditTermsDays: 60,
      taxNumber: 'GST36DDEED4567I4W8',
      customerType: 'retail',
      statusValue: 'Active',
      paymentTermValue: 'Net 60',
      salesRepValue: 'Emily Wilson',
      groupValue: 'Premium',
      notes: 'Electronics and gadgets retailer',
    },
    {
      code: 'RETAIL005',
      name: 'Home Decor Shop',
      email: 'contact@homedecor.com',
      phone: '+91-9876543214',
      mobile: '+91-9876543214',
      contactPerson: 'Kavita Singh',
      contactEmail: 'kavita@homedecor.com',
      contactPhone: '+91-9876543214',
      creditLimit: 15000,
      creditTermsDays: 30,
      taxNumber: 'GST24EEFEE5678J5V9',
      customerType: 'retail',
      statusValue: 'Active',
      paymentTermValue: 'Net 30',
      salesRepValue: 'Robert Brown',
      groupValue: 'Budget',
      notes: 'Home furnishing and decor items',
    },
    {
      code: 'RETAIL006',
      name: 'Sports Equipment',
      email: 'sales@sportsequip.com',
      phone: '+91-9876543215',
      mobile: '+91-9876543215',
      contactPerson: 'Vikram Malhotra',
      contactEmail: 'vikram@sportsequip.com',
      contactPhone: '+91-9876543215',
      creditLimit: 30000,
      creditTermsDays: 30,
      taxNumber: 'GST07FFGFF6789K6U0',
      customerType: 'retail',
      statusValue: 'Active',
      paymentTermValue: 'Net 30',
      salesRepValue: 'John Smith',
      groupValue: 'Standard',
      notes: 'Sports goods and fitness equipment',
    },
    {
      code: 'RETAIL007',
      name: 'Book Store',
      email: 'info@bookstore.com',
      phone: '+91-9876543216',
      mobile: '+91-9876543216',
      contactPerson: 'Meena Gupta',
      contactEmail: 'meena@bookstore.com',
      contactPhone: '+91-9876543216',
      creditLimit: 10000,
      creditTermsDays: 30,
      taxNumber: 'GST33GGHGG7890L7T1',
      customerType: 'retail',
      statusValue: 'Active',
      paymentTermValue: 'COD',
      salesRepValue: 'Sarah Johnson',
      groupValue: 'Budget',
      notes: 'Books and stationery retailer',
    },
    {
      code: 'RETAIL008',
      name: 'Toy Shop',
      email: 'contact@toyshop.com',
      phone: '+91-9876543217',
      mobile: '+91-9876543217',
      contactPerson: 'Ravi Verma',
      contactEmail: 'ravi@toyshop.com',
      contactPhone: '+91-9876543217',
      creditLimit: 18000,
      creditTermsDays: 30,
      taxNumber: 'GST09HHHIH8901M8S2',
      customerType: 'retail',
      statusValue: 'Inactive',
      paymentTermValue: 'Net 30',
      salesRepValue: 'Mike Davis',
      groupValue: 'Standard',
      notes: 'Currently inactive, seasonal business',
    },
    {
      code: 'RETAIL009',
      name: 'Pharmacy',
      email: 'info@pharmacy.com',
      phone: '+91-9876543218',
      mobile: '+91-9876543218',
      contactPerson: 'Dr. Anita Rao',
      contactEmail: 'anita@pharmacy.com',
      contactPhone: '+91-9876543218',
      creditLimit: 40000,
      creditTermsDays: 30,
      taxNumber: 'GST22IIIJI9012N9R3',
      customerType: 'retail',
      statusValue: 'Active',
      paymentTermValue: 'Net 30',
      salesRepValue: 'Emily Wilson',
      groupValue: 'Premium',
      notes: 'Medical supplies and pharmacy',
    },
    {
      code: 'RETAIL010',
      name: 'Grocery Store',
      email: 'sales@grocerystore.com',
      phone: '+91-9876543219',
      mobile: '+91-9876543219',
      contactPerson: 'Ramesh Joshi',
      contactEmail: 'ramesh@grocerystore.com',
      contactPhone: '+91-9876543219',
      creditLimit: 22000,
      creditTermsDays: 30,
      taxNumber: 'GST11JJJKJ0123O0Q4',
      customerType: 'retail',
      statusValue: 'Active',
      paymentTermValue: 'Net 30',
      salesRepValue: 'Robert Brown',
      groupValue: 'Standard',
      notes: 'General grocery and provisions',
    },
  ];

  for (const customer of retailCustomers) {
    await prisma.customer.upsert({
      where: { code: customer.code },
      update: customer,
      create: customer,
    });
  }
  console.log(`    ✓ Created ${retailCustomers.length} retail customers`);

  console.log('  🏭 Seeding Wholesale Customers...');
  
  // Wholesale Customers (5 samples)
  const wholesaleCustomers = [
    {
      code: 'WHOLE001',
      name: 'Metro Wholesale',
      email: 'wholesale@metro.com',
      phone: '+91-9876543220',
      mobile: '+91-9876543220',
      contactPerson: 'Anil Kapoor',
      contactEmail: 'anil@metro.com',
      contactPhone: '+91-9876543220',
      creditLimit: 250000,
      creditTermsDays: 60,
      taxNumber: 'GST29KKKLK1234P1P5',
      customerType: 'wholesale',
      statusValue: 'Active',
      paymentTermValue: 'Net 60',
      salesRepValue: 'John Smith',
      groupValue: 'VIP',
      notes: 'Large wholesale distributor, excellent credit',
    },
    {
      code: 'WHOLE002',
      name: 'Global Traders',
      email: 'info@globaltraders.com',
      phone: '+91-9876543221',
      mobile: '+91-9876543221',
      contactPerson: 'Sanjay Mehta',
      contactEmail: 'sanjay@globaltraders.com',
      contactPhone: '+91-9876543221',
      creditLimit: 300000,
      creditTermsDays: 90,
      taxNumber: 'GST27LLLML2345Q2O6',
      customerType: 'wholesale',
      statusValue: 'Active',
      paymentTermValue: 'Net 90',
      salesRepValue: 'Sarah Johnson',
      groupValue: 'VIP',
      notes: 'International trading company',
    },
    {
      code: 'WHOLE003',
      name: 'Bulk Supplies Inc',
      email: 'sales@bulksupplies.com',
      phone: '+91-9876543222',
      mobile: '+91-9876543222',
      contactPerson: 'Deepak Shah',
      contactEmail: 'deepak@bulksupplies.com',
      contactPhone: '+91-9876543222',
      creditLimit: 180000,
      creditTermsDays: 60,
      taxNumber: 'GST19MMMNM3456R3N7',
      customerType: 'wholesale',
      statusValue: 'Active',
      paymentTermValue: 'Net 60',
      salesRepValue: 'Mike Davis',
      groupValue: 'Premium',
      notes: 'Bulk supplies for commercial customers',
    },
    {
      code: 'WHOLE004',
      name: 'Distribution Center',
      email: 'contact@distcenter.com',
      phone: '+91-9876543223',
      mobile: '+91-9876543223',
      contactPerson: 'Karan Bhatia',
      contactEmail: 'karan@distcenter.com',
      contactPhone: '+91-9876543223',
      creditLimit: 200000,
      creditTermsDays: 60,
      taxNumber: 'GST36NNNNON4567S4M8',
      customerType: 'wholesale',
      statusValue: 'Active',
      paymentTermValue: 'Net 60',
      salesRepValue: 'Emily Wilson',
      groupValue: 'Premium',
      notes: 'Regional distribution center',
    },
    {
      code: 'WHOLE005',
      name: 'Import Export Co',
      email: 'info@impexpco.com',
      phone: '+91-9876543224',
      mobile: '+91-9876543224',
      contactPerson: 'Nisha Aggarwal',
      contactEmail: 'nisha@impexpco.com',
      contactPhone: '+91-9876543224',
      creditLimit: 400000,
      creditTermsDays: 90,
      taxNumber: 'GST24OOOPP5678T5L9',
      customerType: 'wholesale',
      statusValue: 'Active',
      paymentTermValue: 'Net 90',
      salesRepValue: 'Robert Brown',
      groupValue: 'VIP',
      notes: 'Import export operations, long-term partner',
    },
  ];

  for (const customer of wholesaleCustomers) {
    await prisma.customer.upsert({
      where: { code: customer.code },
      update: customer,
      create: customer,
    });
  }
  console.log(`    ✓ Created ${wholesaleCustomers.length} wholesale customers`);

  console.log('  🚚 Seeding Distributor Customers...');
  
  // Distributor Customers (3 samples)
  const distributorCustomers = [
    {
      code: 'DIST001',
      name: 'National Distributor',
      email: 'sales@nationaldist.com',
      phone: '+91-9876543225',
      mobile: '+91-9876543225',
      contactPerson: 'Vijay Malhotra',
      contactEmail: 'vijay@nationaldist.com',
      contactPhone: '+91-9876543225',
      creditLimit: 1500000,
      creditTermsDays: 90,
      taxNumber: 'GST07PPPQP6789U6K0',
      customerType: 'distributor',
      statusValue: 'Active',
      paymentTermValue: 'Net 90',
      salesRepValue: 'John Smith',
      groupValue: 'VIP',
      notes: 'Nationwide distribution network, key account',
    },
    {
      code: 'DIST002',
      name: 'Regional Distribution',
      email: 'info@regionaldist.com',
      phone: '+91-9876543226',
      mobile: '+91-9876543226',
      contactPerson: 'Pooja Desai',
      contactEmail: 'pooja@regionaldist.com',
      contactPhone: '+91-9876543226',
      creditLimit: 800000,
      creditTermsDays: 60,
      taxNumber: 'GST33QQQRQ7890V7J1',
      customerType: 'distributor',
      statusValue: 'Active',
      paymentTermValue: 'Net 60',
      salesRepValue: 'Sarah Johnson',
      groupValue: 'VIP',
      notes: 'Regional distributor for South India',
    },
    {
      code: 'DIST003',
      name: 'Express Logistics',
      email: 'contact@expresslog.com',
      phone: '+91-9876543227',
      mobile: '+91-9876543227',
      contactPerson: 'Rahul Chopra',
      contactEmail: 'rahul@expresslog.com',
      contactPhone: '+91-9876543227',
      creditLimit: 1200000,
      creditTermsDays: 90,
      taxNumber: 'GST09RRRSR8901W8I2',
      customerType: 'distributor',
      statusValue: 'Active',
      paymentTermValue: 'Net 90',
      salesRepValue: 'Mike Davis',
      groupValue: 'VIP',
      notes: 'Express distribution and logistics services',
    },
  ];

  for (const customer of distributorCustomers) {
    await prisma.customer.upsert({
      where: { code: customer.code },
      update: customer,
      create: customer,
    });
  }
  console.log(`    ✓ Created ${distributorCustomers.length} distributor customers`);
}
