// Prisma database connection module
// Note: Prisma client generation requires running: npx prisma generate
// This module provides lazy-loaded Prisma client initialization

let prisma: any = null;
let prismaInitialized = false;

async function getPrismaClient() {
  if (prismaInitialized) {
    return prisma;
  }

  try {
    // Attempt to import Prisma client
    // The client is generated by Prisma during schema changes
    const prismaModule = await import('@prisma/client') as any;
    const PrismaClient = prismaModule.default?.PrismaClient || prismaModule.PrismaClient || prismaModule.default;
    
    if (!PrismaClient) {
      throw new Error('PrismaClient not found in @prisma/client module');
    }

    prisma = new PrismaClient();
    prismaInitialized = true;
    return prisma;
  } catch (error) {
    console.error('Failed to initialize Prisma client:', error);
    // Return a mock object for development if Prisma client is not available
    console.warn('Using mock database connection - Prisma client not available');
    return null;
  }
}

export async function initializeDatabase(): Promise<void> {
  try {
    const client = await getPrismaClient();
    
    if (client) {
      // Test connection
      await client.$connect();
      console.log('Database connected successfully with Prisma');
    } else {
      console.log('Database initialization skipped - Prisma client not available');
      console.log('Run: npx prisma generate');
    }
  } catch (error) {
    console.error('Failed to connect to database:', error);
    // Don't throw - allow server to start even if database connection fails
    console.warn('Server starting without database connection');
  }
}

export async function closeDatabase(): Promise<void> {
  if (prisma && prismaInitialized) {
    try {
      await prisma.$disconnect();
      console.log('Database connection closed');
    } catch (error) {
      console.error('Error closing database connection:', error);
    }
  }
}

export async function getPrisma() {
  return getPrismaClient();
}
